# Generated by Django 3.2.8 on 2023-01-26 14:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10,10}$')])),
                ('hobbies', models.CharField(choices=[('Dance', 'Dance'), ('Cycling', 'Cycling'), ('Reading', 'Reading'), ('Programming', 'Programming'), ('Others', 'Others')], max_length=30)),
                ('messege', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
