# Generated by Django 3.2.8 on 2023-01-28 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
